[tool.black]
line-length = 100

[tool.poetry]
name = "ğŸŒğŸ•¹ï¸ WebPilot"
version = "0.1.0"
description = "Controlling the web - redefined"
authors = ["Amit Nakash"]
readme = "README.md"
packages = [
    { include = "*", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.12.2"
pytest = "7.4.2"
loguru = "0.6.0"
fastapi = "0.109.1"
black = "23.10.0"
pydantic = "1.10.6"
pyppeteer = "1.0.2"
python-dotenv = "1.0.0"
pytest-asyncio = "0.21.1"
pytest-mock = "3.12.0"
uvicorn = "0.23.2"
cachetools = "5.3.3"
tinydb = "^4.8.2"
pymongo = "^4.10.1"
fake-useragent = "^1.5.1"
uvloop = "^0.21.0"
redis = "^5.2.0"
psutil = "^6.1.0"


[build-system]
requires = ["poetry-core"]
